apiVersion: v1
kind: Pod
metadata:
  name: nginx-ingress-controller
spec:
  hostNetwork: true
  containers:
    - name: nginx-ingress-lb
      image: gcr.io/google_containers/nginx-ingress-controller:0.8.3
      env:
        - name: POD_NAME
          value: "nginx-ingress-controller"
        - name: KUBECONFIG
          value: /var/run/kubernetes/kubeconfig
      args:
        - /nginx-ingress-controller
        - --default-backend-service=kube-system/default-http-backend
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/run/kubernetes
          name: kubeconfig
  volumes:
    - name: kubeconfig
      hostPath:
        path: /var/run/kubernetes/
